apiVersion: v1
kind: Service
metadata:
  name: flaskapps
spec:
  selector:
    test: later
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5050
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: flaskappp
  labels:
    test: later
spec:
  containers:
  - image: saigiridharr/myflaskapp
    name: flaskappc
    ports:
    - containerPort: 5050